### ISSUE TITLE
json_intl   >=3.0.1 is incompatible with flutter_localizations from sdk (SDK 3.22.0)

### ISSUE THREAD

**Issue by PSGM** [DavBfr/json_intl#2]
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK. See https://dart.dev/go/sdk-version-pinning for details.

Because json_intl >=3.0.1 depends on intl >=0.17.0 <0.19.0 and every version of flutter_localizations from sdk depends on intl 0.19.0, json_intl
  >=3.0.1 is incompatible with flutter_localizations from sdk.
So, because xxxx depends on both flutter_localizations from sdk and json_intl ^3.0.1, version solving failed.

flutter doctor    
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3593], locale en-ZA)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.4)
[√] Android Studio (version 2022.2)
[√] VS Code, 64-bit edition (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources

**Comment by DavBfr** [comment]
That's updated.
